evaluate:
  type: "shell"
  timeout: 2500
  shell: 
    entrypoint: "python"
    command: 
      - "/evaluate.py"
metric:
  type: "http"
  timeout: 2500
  http:
    method: "GET"
    url: "http://host.docker.internal:8080/api/count"
    successCodes:
      - 200
    parameterMode: query
minReplicas: 0
runMode: "per-resource"
