evaluate:
  type: "shell"
  timeout: 2500
  shell: 
    entrypoint: "python"
    command: 
      - "/evaluate.py"
metric:
  type: "http"
  timeout: 2500
  http:
    method: "GET"
    url: "http://autoscaler:8080/api/count"
    successCodes:
      - 200
    parameterMode: query
minReplicas: 1
maxReplicas: 22
runMode: "per-resource"
logVerbosity: 3
