apiVersion: custompodautoscaler.com/v1
kind: CustomPodAutoscaler
metadata:
  name: http-request
spec:
  template:
    spec:
      containers:
      - name: http-request
        image: olesiapoz/http-request:latest
        imagePullPolicy: Always
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo1
  config:
    - name: interval
      value: "5000"
