kind: PersistentVolumeClaim
apiVersion: v1
metadata: 
  name: azurefile
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Gi
      
