apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata: 
  name: azurefile
provisioner: file.csi.azure.com
allowVolumeExpansion: true
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict
  - actimeo=60
parameters:
  skuName: Standard_LRS