apiVersion: v1
kind: Service
metadata:
  name: demo1-lb
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: phd-demo1
spec:
  type: LoadBalancer
  ports:
  - port: 30036
    targetPort: 30036
  selector:
    app: demo1