apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-alertmanager-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  volumeName: prometheus-alertmanager-pv
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
