apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  labels:
    type: local
    release: prometheus
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/datadrive"
  claimRef:
    name: prometheus-server-pvc
    namespace: default
  persistentVolumeReclaimPolicy: Delete
