apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-server-pvc
  namespace: default
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem
  volumeName: prometheus-server-pv
status:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 8Gi
