apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo1
  labels:
    app: demo1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo1
  template:
    metadata:
      labels:
        app: demo1
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "30036"
        prometheus.io/path: /actuator/prometheus
    spec:
      containers:
        - name: demo1
          image: <enter your registry name>/demo1
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 30036
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 30036
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 30036
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              memory: "1024Mi"
              cpu: "1000m"
            limits:
              memory: "1024Mi"
              cpu: "1000m"

