apiVersion: v1
kind: Pod
metadata:
  name: demo1
  labels:
    app: demo1
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "30036"
    prometheus.io/path: /actuator/prometheus
spec:
  containers:
    - name: demo1
      image: <enter your registry name>/demo1
      imagePullPolicy: Always
      ports:
      - containerPort: 30036
      resources:
        requests:
          memory: "1024Mi"
          cpu: "1000m"
        limits:
            memory: "1024Mi"
            cpu: "1000m"
      livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 30036
          initialDelaySeconds: 10
          periodSeconds: 20
          timeoutSeconds: 3
          failureThreshold: 3
          successThreshold: 1
      readinessProbe:
        httpGet:
          path: /actuator/health/readiness
          port: 30036
        initialDelaySeconds: 10
        periodSeconds: 20
        timeoutSeconds: 3
        failureThreshold: 3
        successThreshold: 1