apiVersion: v1
kind: Service
metadata:
  name: demo1-service
spec:
  selector:
    app: demo1
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 8081
      nodePort: 30036
      targetPort: 8081