apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: demo1
  name: demo1
spec:
  endpoints:
    - path: /actuator/prometheus
      port: http
  namespaceSelector:
    matchNames:
      - demo1
  selector:
    matchLabels:
      app.kubernetes.io/name: demo1